### ISSUE TITLE
Installation for OFv2012

### ISSUE THREAD

**Issue by vbaconnet** [BrechtDevolder-UGent-KULeuven/buoyancyModifiedTurbulenceModels#1]
Hello!

I know this repo is pretty old, but I'm having issues installing it for OFv2012. I followed all the steps explained in the README, but the command `wmake libso` outputs the following error message:

`wmake libso 
wmake: 'Make' directory does not exist in /home/vbaconnet/OpenFOAM/OpenFOAM-v2012
    Searching up directories tree for Make directory
Error: no Make directory for /home/vbaconnet/OpenFOAM/OpenFOAM-v2012`

Is it because of the v2012 version? 

Not sure how to fix it. I would greatly appreciate your help on this! 

Cheers, 

Victor

**Comment by vbaconnet** [comment]
I tried running `wmake libso` from the folder : "buoyancyModifiedTurbulenceModels/OFv1806/".

The command worked, and i got a few compilation warnings. I will try it out today.

**Comment by LJM-97** [comment]
@vbaconnet  Hi!

Could you please explain how this issue is resolved? Can you give a general overview of the specific solution?
